spring.application.name=config-server

spring.cloud.config.server.git.url=https://github.com/TheBugHunter-HimanshuBagga/Ecommerce-ConfigServer-/tree/main
spring.cloud.config.server.git.username=TheBugHunter-HimanshuBagga
spring.cloud.config.server.git.password=github_pat_11BWAEQAQRJmnZzu1YvelpJYYFnabmygVIeVsMqMEAwrmoSOYXNDM2pqX5IC3L
spring.cloud.config.server.git.default-label=main

server.port=8888
eureka.client.service.url.defaultZone=http://localhost:8761/eureka

